/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bmiara;

import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bmi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tinggibadan = new javax.swing.JLabel();
        beratbadan = new javax.swing.JLabel();
        bmi2 = new javax.swing.JLabel();
        jTextField1tinggibadan = new javax.swing.JTextField();
        jTextField2beratbadan = new javax.swing.JTextField();
        jTextField3bmi2 = new javax.swing.JTextField();
        Buttonhitung = new javax.swing.JButton();
        Buttonhapus = new javax.swing.JButton();
        Buttonkeluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        hasilcalculate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        bmi.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        bmi.setText("Body Mass Index");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bmi)
                .addGap(217, 217, 217))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bmi)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tinggibadan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tinggibadan.setText("Tinggi Badan (m)");

        beratbadan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        beratbadan.setText("Berat Badan (kg)");

        bmi2.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        bmi2.setText("Body Mass Index (BMI)");

        jTextField1tinggibadan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1tinggibadanActionPerformed(evt);
            }
        });

        jTextField2beratbadan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2beratbadanActionPerformed(evt);
            }
        });

        jTextField3bmi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3bmi2ActionPerformed(evt);
            }
        });

        Buttonhitung.setBackground(new java.awt.Color(102, 102, 255));
        Buttonhitung.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Buttonhitung.setText("Hitung");
        Buttonhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonhitungActionPerformed(evt);
            }
        });

        Buttonhapus.setBackground(new java.awt.Color(102, 102, 255));
        Buttonhapus.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Buttonhapus.setText("Hapus");
        Buttonhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonhapusActionPerformed(evt);
            }
        });

        Buttonkeluar.setBackground(new java.awt.Color(102, 102, 255));
        Buttonkeluar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Buttonkeluar.setText("Keluar");
        Buttonkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonkeluarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bmi2)
                            .addComponent(beratbadan)
                            .addComponent(tinggibadan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2beratbadan, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                    .addComponent(jTextField1tinggibadan))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField3bmi2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Buttonhitung)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(hasilcalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Buttonhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(Buttonkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tinggibadan)
                    .addComponent(jTextField1tinggibadan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beratbadan)
                    .addComponent(jTextField2beratbadan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hasilcalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bmi2)
                        .addComponent(jTextField3bmi2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buttonkeluar)
                    .addComponent(Buttonhapus)
                    .addComponent(Buttonhitung))
                .addGap(17, 17, 17))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmiara/bmipp.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1tinggibadanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1tinggibadanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1tinggibadanActionPerformed

    private void jTextField2beratbadanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2beratbadanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2beratbadanActionPerformed

    private void ButtonhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonhapusActionPerformed
        jTextField1tinggibadan.setText("");
        jTextField2beratbadan.setText("");
        jTextField3bmi2.setText("");
        jTextField3bmi2.setOpaque(true);
        jTextField3bmi2.setBackground(null);
        hasilcalculate.setText("");
        
    }//GEN-LAST:event_ButtonhapusActionPerformed

    private void ButtonkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonkeluarActionPerformed
       System.exit(0);
    }//GEN-LAST:event_ButtonkeluarActionPerformed

    private void ButtonhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonhitungActionPerformed
        double h = Double.parseDouble(jTextField1tinggibadan.getText());
        double w = Double.parseDouble(jTextField2beratbadan.getText());
        
        double bmiara = w / (h * h);
        
        String cal = String.format("%.2f",bmiara);
        
        jTextField3bmi2.setText(cal);
        
        if(bmiara <= 18.5)
        {
            jTextField3bmi2.setOpaque(true);
            jTextField3bmi2.setBackground(Color.blue);
            hasilcalculate.setForeground(Color.blue);
            hasilcalculate.setText("Kurang berat badan");
        }
        else if(bmiara <= 22.9)
        {
            jTextField3bmi2.setOpaque(true);
            jTextField3bmi2.setBackground(Color.green);
            hasilcalculate.setForeground(Color.green);
            hasilcalculate.setText("Normal");
        }
        else if(bmiara <= 24.9)
        {
            jTextField3bmi2.setOpaque(true);
            jTextField3bmi2.setBackground(Color.yellow);
            hasilcalculate.setForeground(Color.yellow);
            hasilcalculate.setText("Kelebihan berat badan");
        }
        else if(bmiara <= 29.9)
        {
            jTextField3bmi2.setOpaque(true);
            jTextField3bmi2.setBackground(Color.orange);
            hasilcalculate.setForeground(Color.orange);
            hasilcalculate.setText("Obesitas tingkat 1");
        }
        else if(bmiara >= 30)
        {
            jTextField3bmi2.setOpaque(true);
            jTextField3bmi2.setBackground(Color.red);
            hasilcalculate.setForeground(Color.red);
            hasilcalculate.setText("Obesitas tingkat 2");
        }
        
    }//GEN-LAST:event_ButtonhitungActionPerformed

    private void jTextField3bmi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3bmi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3bmi2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonhapus;
    private javax.swing.JButton Buttonhitung;
    private javax.swing.JButton Buttonkeluar;
    private javax.swing.JLabel beratbadan;
    private javax.swing.JLabel bmi;
    private javax.swing.JLabel bmi2;
    private javax.swing.JLabel hasilcalculate;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1tinggibadan;
    private javax.swing.JTextField jTextField2beratbadan;
    private javax.swing.JTextField jTextField3bmi2;
    private javax.swing.JLabel tinggibadan;
    // End of variables declaration//GEN-END:variables
}
